INSERT INTO EMPRESA.CARGO (NOME) 
	VALUES ('Analista Desenvolvedor Pleno');

INSERT INTO EMPRESA.DEPARTAMENTO (NOME) 
	VALUES ('Desenvolvimento de Aplicações');

INSERT INTO EMPRESA.FUNCIONARIO (NOME, DT_NASCIMENTO, DT_CONTRATACAO, CARGO_ID, DEPARTAMENTO_ID) 
	VALUES ('Sebastião Martins Pereira', '1989-04-24', '2016-09-25 15:36:47.678'
                ,(SELECT MAX(ID_CARGO) FROM EMPRESA.CARGO)
                ,(SELECT MAX(ID_DEPARTAMENTO) FROM EMPRESA.DEPARTAMENTO));

UPDATE EMPRESA.CARGO
SET NOME = 'ANALISTA DESENVOLVEDOR SÊNIOR'
WHERE EMPRESA.CARGO.ID_CARGO = (SELECT MAX(ID_CARGO) FROM EMPRESA.CARGO);

UPDATE EMPRESA.DEPARTAMENTO
SET NOME = 'PROGRAMAÇÃO'
WHERE  EMPRESA.DEPARTAMENTO.ID_DEPARTAMENTO  = (SELECT MAX(ID_DEPARTAMENTO) FROM EMPRESA.DEPARTAMENTO);


UPDATE EMPRESA.FUNCIONARIO
SET NOME = 'Sebastião Martins Pereira'
WHERE EMPRESA.FUNCIONARIO.ID_FUNCIONARIO = (SELECT MAX(ID_FUNCIONARIO) FROM EMPRESA.FUNCIONARIO);

DELETE 
FROM EMPRESA.CARGO
WHERE EMPRESA.CARGO.ID_CARGO = (SELECT MAX(ID_CARGO) FROM EMPRESA.CARGO);

DELETE 
FROM EMPRESA.DEPARTAMENTO
WHERE EMPRESA.DEPARTAMENTO.ID_DEPARTAMENTO = (SELECT MAX(ID_DEPARTAMENTO) FROM EMPRESA.DEPARTAMENTO);

DELETE
FROM EMPRESA.FUNCIONARIO
WHERE EMPRESA.FUNCIONARIO.ID_FUNCIONARIO = (SELECT MAX(ID_FUNCIONARIO) FROM EMPRESA.FUNCIONARIO);

SELECT * 
FROM EMPRESA.CARGO;

SELECT * 
FROM EMPRESA.DEPARTAMENTO;

SELECT ID_FUNCIONARIO,FUNCIONARIO.NOME,DT_NASCIMENTO,DT_CONTRATACAO,CARGO_ID,CARGO.NOME,DEPARTAMENTO_ID,DEPARTAMENTO.NOME
FROM EMPRESA.FUNCIONARIO
INNER JOIN EMPRESA.CARGO ON EMPRESA.CARGO.ID_CARGO = EMPRESA.FUNCIONARIO.CARGO_ID
INNER JOIN EMPRESA.DEPARTAMENTO ON EMPRESA.DEPARTAMENTO.ID_DEPARTAMENTO = EMPRESA.FUNCIONARIO.DEPARTAMENTO_ID;
